language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

env:
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=master

matrix:
  exclude:
    - { python: "2.7", env: DJANGO=2.0 }
    - { python: "2.7", env: DJANGO=master }
    - { python: "3.4", env: DJANGO=master }
    - { python: "3.6", env: DJANGO=1.10 }

  fast_finish: true
  allow_failures:
      - env: DJANGO=master

install:
  - pip install tox tox-travis

script:
  - tox
